django_item_trade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include("users.urls")),
    path('products/',include("items.urls")),
    path('',include("item_trade_page.urls")),
    path('cart/',include("shopping_cart.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item_trade_page/urls.py
from django.urls import path

from . import views

app_name = "item_trade"

urlpatterns = [
    path("",views.home_page, name = "home_page"),
    path("logout/",views.logout_view, name = "logout"),
    path("login-page/",views.login_page, name = "login_page"),
    path("signup-page/",views.signup_page, name = "signup_page"),
    path("buy-credit/<int:user_id>",views.credit_page, name = "credit_page"),
    path('create-product/', views.create_product_view, name='create_product'),
    path('product-info/<str:product_type>/<int:product_id>', views.product_info_page, name = "product_info"),
    path('product-purchase/<str:product_type>/<int:product_id>',views.product_purchase_page, name = "product_purchase"),
    path('buy-the-product',views.buy_the_product, name = "buy_the_product"),
    path('payment-fail',views.payment_fail, name = "payment_fail"),
    path("kakaopay/<str:user_name>", views.kakaopay, name = "kakaopay"),
    path('paySuccess/', views.paySuccess),
    path('payFail/', views.payFail),
    path('payCancel/', views.payCancel),
    path('my-page/',views.my_page, name = "my_page"),
    path('cart/',views.shopping_cart, name = "shopping_cart"),
    path('cart-destory/<int:product_id>/<str:product_type>',views.shopping_cart_destory, name = "shopping_cart_destory"),
    path('product-info-handle',views.prduct_info_page_handle, name = "product_info_handle"),
    path('game',views.game_page, name = "game_page"),
]

items/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('game/',views.GameView.as_view({"get":"list"})),
    path('game/<int:pk>/',views.GameView.as_view({"get" : "get_game_list"})),
    path('create/', views.CreateProductView.as_view(), name='create_product'),
    path('get-recently-create-item/',views.ProductViewsets.as_view({
        "get":"get_recently_create_item",
    })),
    path("get-product-info/<str:product_type>/<int:product_id>/",views.ProductViewsets.as_view({
        "get" : "get_product_info"
    })),
    path("buy-product/",views.ProductViewsets.as_view({
        "post" : "buy_the_product"
    }),name='buy_the_product'),
    path("purchase-record/",views.PurchaseRecordViewset.as_view({'get': 'list'}), name='purchase_record'),
    path('purchases/<int:pk>/', views.PurchaseRecordViewset.as_view({'get': 'list'}), name='purchase-detail'),
]

shopping_cart/urls.py
from django.urls import path

from . import views

app_name = "shopping_cart"

urlpatterns = [
    path('cart/', views.CartViewSet.as_view({'get': 'list'}), name='cart-list'),
    path('cart/<int:pk>/', views.CartViewSet.as_view({'get': 'retrieve'}), name='cart-detail'),

    path('cart-items/', views.CartItemViewSet.as_view({'get': 'list', 'post': 'create'}), name='cart-item-list'),
    path('cart-items/<int:user_id>/<int:product_id>/<str:product_type>/', views.CartItemViewSet.as_view({'delete': 'destroy'}), name='cart-item-detail'),
]

item_trade_page/models.py
from django.db import models

# Create your models here.

shopping_cart/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart of "+self.user.username
    
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="items")  
    product_id = models.PositiveBigIntegerField() 
    product_type = models.CharField(max_length=20) 
    title = models.CharField(max_length=150) 
    price = models.DecimalField(max_digits=10, decimal_places=2) 

    class Meta:
        unique_together = ("cart", "product_id", "product_type")  # 중복 추가 방지

    def __str__(self):
        return f"{self.title} in {self.cart.user.username}'s cart"

item_trade_page/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
# Create your views here.

from .froms import ProductForm
import requests
import json

#User
from users.serializers import SignUpSerializer,LoginSerializer, UserCredit
from django.contrib.auth import login,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from users.models import UserCredit

from shopping_cart.models import Cart,CartItem

API_PATH = "http://127.0.0.1:8001/"

# ---------------------------------------- 매인 페이지 관련 ------------------------------------------- #
def home_page(request):
    # 매인 페이지 관련 함수
    # item app에서 최근 등록된 3개 상품 찾아와 보여주도록 설정정
    path = "http://127.0.0.1:8001/products/get-recently-create-item"
    items = {}
    
    res = requests.get(path)
    items = res.json()

    path = "http://127.0.0.1:8001/products/game"
    re = requests.get(path)
    game = re.json()
    
    
    table_data = {
        "account_data" : items["account_data"],
        "item_data" : items["item_data"],
        "game_money_data" : items["game_money_data"]
    }
    
    return render(request,"item_trade_page/home_page.html",{"user" : request.user,"table_data":table_data,"game":game})

def login_page(request):
    # 로그인 페이지 관련 함수
    if request.method == "POST":
        serializer = LoginSerializer(data = request.POST)

        if serializer.is_valid():
            token = serializer.validated_data
            user = User.objects.get(auth_token = token)
            # 이메일로 로그인하기 위해서 백앤드 부분을 제작함함
            user.backend = 'users.backends.EmailAuthBackend' # 제작한 백앤드 설정
            login(request, user)
            return redirect("item_trade:home_page")
        else:
            for error in serializer.errors.values():
                print(error[0])
                messages.error(request, error[0])

    return render(request,"item_trade_page/login_page.html")

def signup_page(request):
    # 회원가입 페이지 관련 함수수
    if request.method == "POST":
        serializer = SignUpSerializer(data = request.POST)
        
        if serializer.is_valid():
            user = serializer.save()
            messages.success(request, "회원가입 성공하였습니다.")
            user.backend = 'users.backends.EmailAuthBackend' # 제작한 백앤드 설정
            login(request, user)
            return redirect("item_trade:home_page")
        else:
            for error in serializer.errors.values():
                messages.error(request, error[0])
    
    return render(request, "item_trade_page/signup_page.html")

@login_required # 로그인이 필요한 뷰
def logout_view(request):
    # 로그아웃
    logout(request)
    return redirect("item_trade:home_page")

def game_page(request):
    selscted_game_id = request.GET.get("selected_game")
    
    path = API_PATH + "products/game/{}".format(int(selscted_game_id))
    res = requests.get(path)
    game_list = res.json()
    print("@@@@@")
    print(game_list)
    print("@@@@@")

    game_lists = {
        "game" : game_list["game"],
        "account_data" : game_list["account_data"],
        "item_data" : game_list["item_data"],
        "game_money_data" : game_list["game_money_data"]
    }
    

    return render(request, "item_trade_page/game_page.html", {"game_lists":game_lists})

# ---------------------------------------- 상품 등록 관련 ------------------------------------------- #

@login_required # 로그인이 필요한 뷰
def create_product_view(request):
    # 상품 등록 관련 함수
    form = ProductForm()  # 기본 폼

    if request.method == "POST":
       
        selected_game = request.POST.get("game")
        user = request.user.id
        product_type = request.POST.get("product_type")

        data = {
            "game" : selected_game,
            "title" : request.POST.get("title"),
            "seller" : user,
            "product_type" : product_type,
            "description" : request.POST.get("description"),
        }
      
        if product_type == "account": 
            data["account_class"] = request.POST.get("account_class")
            data["price"] = request.POST.get("price")
        
        elif product_type == "item":
            data["item_name"] = request.POST.get("item_name")
            data["quantity"] = request.POST.get("quantity")
            data["price_per_item"] = int(request.POST.get("price_per_item"))
        
        elif product_type == "game_money":
            data["total_amount"] = request.POST.get("total_amount")
            data["total_price"] = request.POST.get("total_price")

        # 이미지 넘기기기
        files = []
        if request.FILES.getlist('images'):
            for image in request.FILES.getlist('images'):
                files.append(('product_image', image))

        respone = requests.post(API_PATH+"products/create/",data=data, files=files)
        
        if respone.status_code == 201:
            return redirect("item_trade:home_page")  

    return render(request, 'item_trade_page/create_product.html', {'form': form})

# ---------------------------------------- 상품 상세페이지 및 상품 구매매 관련 ------------------------------------------- #
@login_required # 로그인이 필요한 뷰
def product_info_page(request,product_type,product_id):
    # 상품 상세페이지 관련 함수
    respone = requests.get(API_PATH+"products/get-product-info/{}/{}".format(product_type,product_id))
    product_data = respone.json()

    return render(request, "item_trade_page/product_info_page.html",product_data)

@login_required # 로그인이 필요한 뷰
def product_purchase_page(request,product_type,product_id):
    # 결제 페이지 관련 함수 ( 장바구니에서 사용할 예정 )
    respone = requests.get(API_PATH+"products/get-product-info/{}/{}".format(product_type,product_id))
    product_data = respone.json()

    # 최종 결제 함수에서 데이터 사용하기 위해서 session에 저장한다
    request.session["product_data"] = product_data

    res = requests.get(API_PATH+"cart/cart-items/{}".format(product_id))

    return render(request, "item_trade_page/product_purchase_page.html",product_data)

@login_required # 로그인이 필요한 뷰
def buy_the_product(request): 
    # 상품 최종 결제 함수
    if request.method == "POST":
        product_data = request.session.get("product_data")["product_data"][0]
        product_id = product_data["id"]
        product_type = product_data["product_type"]

        api_url = API_PATH + "products/buy-product/"
        headers = {"Content-Type": "application/json"}
        data = {
            "product_id" : product_id,
            "product_type" : product_type,
            "user_id" : request.user.id
        }
        
        respone = requests.post(api_url, headers=headers , data=json.dumps(data, ensure_ascii=False))

        if respone.status_code == 200:
            return redirect("item_trade:home_page") 
        else:
            error_message = respone.json()
            return render(request, "item_trade_page/payment_fail.html", {"error": error_message})
        
@login_required # 로그인이 필요한 뷰
def payment_fail(request):
    # 최종 결제할 때 크레딧 부족으로 실패할 경우 보여주기 위한 페이지지
    return render(request, "item_trade_page/payment_fail.html", {"error": "사용자 크레딧이 부족합니다."})

# ---------------------------------------- 크레딧 결제 관련 ------------------------------------------- #
@login_required # 로그인이 필요한 뷰
def credit_page(request,user_id):
    # 크레딧 충전 페이지
    user_credit = UserCredit.objects.get(user__id= user_id)

    return render(request, "item_trade_page/credit_page.html",{"user_credit":user_credit})

@login_required # 로그인이 필요한 뷰
def kakaopay(request,user_name):
    # 크레딧 충전을 하기위해 카카오페이 api를 사용하여 충전하도록 제작작
    if request.method == 'POST':
        credit = int(request.POST.get('credit', 0))

        if credit < 5:
            return render(request, 'payFail.html')

        total_amount = credit * 1000
        
        admin_key = 'DEV8038EAA952F7A2BA70FE945F590AB63779A1D'
        url = f'https://open-api.kakaopay.com/online/v1/payment/ready'
        headers = {
            'Authorization': f'SECRET_KEY {admin_key}',
            "Content-Type": "application/json"
        }

        data = {
            'cid': 'TC0ONETIME', # 테스트용 CID, 상용은 발급받은 CID 사용
            'partner_order_id':'order_id_12345',  # 고유 주문 ID
            'partner_user_id': user_name, # 사용자 ID
            'item_name':'Creadit',
            'quantity': credit,  # 수량 (0이 아닌 양수)
            'total_amount': int(total_amount), # 총 가격
            'vat_amount': 200, # 부가세
            'tax_free_amount': 0, # 비과세
            'approval_url':'http://127.0.0.1:8001/paySuccess/', 
            'fail_url':'http://127.0.0.1:8001/payFail',
            'cancel_url':'http://127.0.0.1:8001/payCancel'
        }

        res = requests.post(url, data=json.dumps(data, ensure_ascii=False), headers=headers)

        result = res.json()
        request.session['tid'] = result['tid']
        request.session["user"] = data["partner_user_id"]
        request.session["credit"] = data["quantity"]
        return redirect(result['next_redirect_pc_url'])
     
    return render(request, "item_trade_page/payFail.html")  

def paySuccess(request):
    admin_key = 'DEV8038EAA952F7A2BA70FE945F590AB63779A1D'
    url = 'https://open-api.kakaopay.com/online/v1/payment/approve'
    headers = {
        'Authorization': f'SECRET_KEY {admin_key}',
        "Content-Type": "application/json"
    }
    data = {
        'cid':'TC0ONETIME',
        'tid': request.session['tid'],
        'partner_order_id':'order_id_12345',
        'partner_user_id': request.session['user'],
        'pg_token': request.GET['pg_token']
    }
    res = requests.post(url, data=json.dumps(data, ensure_ascii=False), headers=headers)
    result = res.json()

    if result.get('msg'):
        return redirect('/payFail')
    else:
        user = User.objects.get(username = request.session['user'])
        user_credit = UserCredit.objects.get(user=user)
        user_credit.credit += request.session["credit"]  # 기존 크레딧에 추가
        user_credit.save()  # 저장
        return redirect("item_trade:home_page")  
    
def payFail(request):
    return render(request, 'payFail.html')

shopping_cart/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from .models import Cart, CartItem
from .serializers import CartSerializer, CartItemSerializer
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User

class CartViewSet(viewsets.ModelViewSet):
    queryset = Cart.objects.all()
    serializer_class = CartSerializer

    def get_queryset(self):
        # 현재 로그인한 사용자에 대한 장바구니만 반환
        return Cart.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        # 장바구니는 각 사용자마다 하나만 생성
        if not Cart.objects.filter(user=self.request.user).exists():
            serializer.save(user=self.request.user)

class CartItemViewSet(viewsets.ModelViewSet):
    queryset = CartItem.objects.all()
    serializer_class = CartItemSerializer

    def get_queryset(self):
        # 로그인한 사용자의 장바구니 아이템만 반환
        return CartItem.objects.filter(cart__user=self.request.user)

    def create(self, request, *args, **kwargs):
        user_id = request.data.get("user")
        user = get_object_or_404(User, id = user_id)
        cart, created = Cart.objects.get_or_create(user=user)  # 장바구니 생성 또는 가져오기
        data = request.data.copy()
        data['cart'] = cart.id  # 요청 데이터에 장바구니 ID 추가
        
        existing_item = CartItem.objects.filter(cart = cart, product_id=data['product_id'], product_type=data['product_type']).first()

        if existing_item:
            return Response({"detail": "Item already exists in the cart."}, status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(data = data)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response(serializer.data, status=status.HTTP_201_CREATED)
    
    def destroy(self, request, *args, **kwargs):
        user_id = kwargs.get("user_id")
        product_id = kwargs.get("product_id")
        product_type = kwargs.get("product_type")

        user = get_object_or_404(User,id = user_id)
        cart = get_object_or_404(Cart,user=user)

        cart_item = CartItem.objects.filter(cart=cart,product_id = product_id,product_type = product_type).first()
        cart_item.delete()

        return Response({"detail": "Item removed from cart."}, status=status.HTTP_204_NO_CONTENT)

item_trade_page/templates/item_trade_page/credit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>크레딧 구매</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            padding: 20px;
            line-height: 1.6;
            background-color: rgb(158, 158, 158);
        }
        h1 {
            font-size: 24px;
            margin-bottom: 10px;
        }
        p {
            margin-bottom: 20px;
            color: #555;
        }
        .container {
            display: inline-block;
            text-align: left;
            max-width: 500px;
        }
        .input-group {
            margin-bottom: 15px;
        }
        label {
            display: block;
            font-size: 16px;
            margin-bottom: 5px;
        }
        input[type="number"] {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        .total {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 20px;
        }
        .btn {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            color: white;
            background-color: #007bff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        .btn:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>크레딧 구매</h1>
    <p>플랫폼 모든 콘텐츠에 사용하는 크레딧을 구매하세요!. 최소 구매 금액은 5크레딧입니다. 1 크레딧 1000원 입니다.</p>
    <label for="credit">현재 {{user_credit.user.username}}님의 크레딧 : {{user_credit.credit}}</label>

    

    <form method="post" action="{% url 'item_trade:kakaopay' user.username %}">
        {% csrf_token %}
        <div class="container">
            <div class="input-group">
                <label for="credit">크레딧 수</label>
                <input type="number" id="credit" name="credit" min="5" placeholder="크레딧 수를 입력하세요" oninput="calculateTotal()">
            </div>
            <div class="total">총계: <span id="total">0</span> </div>
            <button class="btn">크레딧 구매</button>
        </div>
    </form>

    <script>
        function calculateTotal() {
            const creditInput = document.getElementById('credit').value;
            const totalElement = document.getElementById('total');
            const creditCount = parseInt(creditInput, 10) || 0;
            const total = creditCount * 1000; // 1 크레딧당 1000원
            totalElement.textContent = total.toLocaleString() + ' 원';
        }
    </script>
</body>
</html>

item_trade_page/templates/item_trade_page/game_page.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>메인 페이지</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: rgb(158, 158, 158);
        }
        header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 20px;
            background-color: #f5f5f5;
            border-bottom: 1px solid #ddd;
        }
        header .logo {
            font-size: 24px;
            font-weight: bold;
        }
        /* header .search-bar {
            flex: 1;
            margin: 0 20px;
        }
        header .search-bar input {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
        } */
        .wide-dropdown {
            width: 500px; /* 드롭다운의 가로 크기 */
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            background-color: white;
            cursor: pointer;
        }

        .search-bar {
            margin: 0 20px;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        header .buttons button {
            margin-left: 10px;
            padding: 8px 15px;
            border: none;
            border-radius: 4px;
            background-color: #007bff;
            color: white;
            cursor: pointer;
        }
        header .buttons button:hover {
            background-color: #0056b3;
        }
        .benefits {
            display: flex;
            justify-content: space-around;
            margin: 20px;
            padding: 20px;
            background-color: #f9f9f94a;
            border: 1px solid #eee;
        }
        .benefit {
            text-align: center;
            width: 30%;
        }
        .benefit img {
            width: 50px;
            height: 50px;
            margin-bottom: 10px;
        }
        .benefit h3 {
            font-size: 16px;
            margin-bottom: 10px;
        }
        .benefit p {
            font-size: 14px;
            color: #666;
        }
        .latest-items {
            margin: 20px;
        }
        .latest-items h2 {
            margin-bottom: 10px;
            font-size: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table th, table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }
        table th {
            background-color: #f9f9f94a;
        }
    </style>
</head>
<body>
    <header>
        <div class="logo"><a href="{% url 'item_trade:home_page' %}">로고</a></div>
        <!-- <div class="search-bar">
            <form action="{% url 'item_trade:game_page' %}" method="get">
                <select name="selected_game" id="game-select" class="wide-dropdown" onchange="this.form.submit()">
                    <option value="" {% if not selected_game %}selected{% endif %}>게임 선택</option>
                    {% for item in game %}
                        <option value="{{ item.id }}" {% if selected_game == item.id %}selected{% endif %}>{{ item.name }}</option>
                    {% endfor %}
                </select>
            </form>
        </div> -->
        
        {% if not user.is_authenticated %}
            <div class="buttons">
                <a href="{% url 'item_trade:signup_page' %}"><button>회원가입</button></a>
                <a href="{% url 'item_trade:login_page' %}"><button>로그인</button></a>
            </div>
        {% else %}
            <div class="buttons">
                <a href="{% url 'item_trade:logout' %}" style="margin-left: 10px;">로그아웃</a>
                <a href="{% url 'item_trade:create_product' %}"><button>상품 등록</button></a>
                <a href="{% url 'item_trade:my_page' %}"><button>마이 페이지</button></a>
                <a href="{% url 'item_trade:credit_page' user.id %}"><button>크래딧 충전</button></a>
                <a href="{% url 'item_trade:shopping_cart' %}"><button>장바 구니</button></a>
            </div>
        {%endif%}
    </header>
    <section class="latest-items">
        <h1>{{game_lists.game}}</h1>
        <h2> 계정 </h2>
        <table>
            <thead>
                <tr>
                    <th>Game</th>
                    <th>Title</th>
                    <th>Class</th>
                    <th>Price</th>
                    <th>Seller</th>
                </tr>
            </thead>
            <tbody>
                {% for account in game_lists.account_data %}
                    <tr onclick="location.href='{% url 'item_trade:product_info' account.product_type account.id %}'" style="cursor: pointer;">
                        <th>{{account.game}}</th>
                        <th>{{account.title}}</th>
                        <th>{{account.account_class}}</th>
                        <th>{{account.price}}</th>
                        <th>{{account.seller}}</th>
                    </tr>
                {%endfor%}
            </tbody>
        </table>
        <br><br><br>
        <h2> 아이템 </h2>
        <table>
            <thead>
                <tr>
                    <th>Game</th>
                    <th>Title</th>
                    <th>Item Name</th>
                    <th>Quantity</th>
                    <th>Price Per Item</th>
                    <th>Seller</th>
                </tr>
            </thead>
            <tbody>
                {% for item in game_lists.item_data %}
                    <tr onclick="location.href='{% url 'item_trade:product_info' item.product_type item.id %}'" style="cursor: pointer;">
                        <th>{{item.game}}</th>
                        <th>{{item.title}}</th>
                        <th>{{item.item_name}}</th>
                        <th>{{item.quantity}}</th>
                        <th>{{item.price_per_item}}</th>
                        <th>{{item.seller}}</th>
                    </tr>
                {%endfor%}
            </tbody>
        </table>
        <br><br><br>
        <h2> 게임 머니 </h2>
        <table>
            <thead>
                <tr>
                    <th>Game</th>
                    <th>Title</th>
                    <th>Total Amount</th>
                    <th>Total Price</th>
                    <th>Seller</th>
                </tr>
            </thead>
            <tbody>
                {% for game_money in game_lists.game_money_data %}
                    <tr onclick="location.href='{% url 'item_trade:product_info' game_money.product_type game_money.id %}'" style="cursor: pointer;">
                        <th>{{game_money.game}}</th>
                        <th>{{game_money.title}}</th>
                        <th>{{game_money.total_amount}}</th>
                        <th>{{game_money.total_price}}</th>
                        <th>{{game_money.seller}}</th>
                    </tr>
                {%endfor%}
            </tbody>
        </table>
    </section>
</body>
</html>

item_trade_page/templates/item_trade_page/payCancel.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h4>결제 취소</h4>
    <a href="/kakaoPay">HOME</a>
</body>
</html>

item_trade_page/templates/item_trade_page/payFail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>결제 실패</h2>
    <a href="/kakaoPay">HOME</a>
</body>
</html>

item_trade_page/templates/item_trade_page/paySuccess.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>결제 성공</h2>
    <a href="/kakaoPay">HOME</a>
</body>
</html>

item_trade_page/templates/item_trade_page/shopping_cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Shopping Cart</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: rgb(158, 158, 158);
        }
        .header {
            background-color: #e3f2fd;
            padding: 10px 20px;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }
        .header h1 {
            font-size: 20px;
            margin: 0;
        }
        .container {
            max-width: 800px;
            margin: 20px auto;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }
        .order-date {
            font-weight: bold;
            font-size: 16px;
            margin-bottom: 10px;
        }
        .order-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #ddd;
            padding: 10px 0;
        }
        .order-item:last-child {
            border-bottom: none;
        }
        .order-item img {
            width: 80px;
            height: 80px;
            border-radius: 8px;
            margin-right: 20px;
        }
        .order-details {
            flex: 1;
        }
        .order-details h2 {
            font-size: 14px;
            margin: 0 0 5px;
        }
        .order-details p {
            margin: 0;
            color: #555;
        }
        .order-actions {
            text-align: center;
        }
        .order-actions button {
            background-color: #007bff;
            color: white;
            border: none;
            padding: 8px 12px;
            border-radius: 4px;
            cursor: pointer;
        }
        .order-actions button:hover {
            background-color: #0056b3;
        }
        .view-details {
            text-align: right;
            margin-top: 10px;
        }
        .view-details a {
            text-decoration: none;
            color: #007bff;
            font-size: 14px;
        }
        .view-details a:hover {
            text-decoration: underline;
        }
        .history {
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>Shopping Cart</h1>

    <!-- 장바구니 목록 -->
    <ul>
        {% if not cart == None %}
            {% for item in cart %}
                <div class="container">
                    <div class="order-item">
                        <div class="order-details">
                            <h2>{{ item.title }}</h2>
                            <p>{{ item.price }} 크레딧</p>
                        </div>
                    </div>
                    <div class="view-details">
                        <a href="{% url 'item_trade:product_purchase' item.product_type item.product_id %}"><button>구매하기</button></a>
                        <a href="{% url 'item_trade:shopping_cart_destory' item.product_id item.product_type %}"><button>삭제하기</button></a>
                    </div>
                </div>
                {% endfor %}
        {% else %}
            <div class = "container">
                <div class="no-products">
                    <p>상품이 없습니다.</p>
                </div>  
            </div>
        {% endif %}
    </ul>
</body>
</html>